### ISSUE TITLE
Upgrade to AIR 33 is not AIR 32 compatible

### ISSUE THREAD

**Issue by fudosakura** [tuarua/Firebase-ANE#38] opened 2019-10-24 12:25 UTC
Answer the below. **DO NOT DELETE!!**

- **Have you read the README and wiki carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
    0.6.0

- **With which operating system?**
    - iOS 11, Android 7 etc?

- **From which operating system?**
    - Win10

- **Which IDE are you using?**
    - VSCode

- **Which version of AIR are you using?**
    - 32

- **What steps will reproduce the problem?**
    - If you try to build using AIR 32 it will complain about bad class file magic, Fixed it by patching 0.5.0 classes.jar files and rebuild the ane.

- **What is the expected output? What do you see instead?**
bad class file magic (cafebabe) or version (0034.0000)

**Comment by tuarua** [comment] 2019-10-24 13:24
Duplicate of #36

https://github.com/tuarua/Firebase-ANE/issues/36#issuecomment-534472280

**Closed by tuarua** 2019-10-24 13:24 UTC
